language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
install:
  - pip install -r requirements.txt
env:
  - DIR_1=extract
  - DIR_2=validate
script:
  - cd $DIR_1 && python metaextract.py
  - cd $DIR_2 && python validate.py