language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-console-scripts
script:
  - pytest -vv
notifications:
  email: false