language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
install:
  - pip install -r requirements.txt
script:
  - cd extract && python metaextract.py -i"tests" -o"json" -e"tests"
  - cd ../validate && python validate.py -s"../schema/json/o2r-meta-schema.json" -c"../schema/json/example1-valid.json"