language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install -r requirements.txt
script:
  - cd extract && python metaextract.py -i"tests" -o"tests"
  - cd ../broker && python metabroker.py -m"o2r-map.json" -i"tests" -o"tests"
  - cd ../validate && python metavalidate.py -s"../schema/json/o2r-meta-schema.json" -c"../schema/json/example1-valid.json"
  - cd ../validate && python metavalidate.py -s"../schema/json/o2r-meta-ui-schema.json" -c"../schema/json/example2-ui-valid.json"
