language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install git+https://github.com/Toblerity/Fiona.git
script:
  - python o2rmeta.py -debug extract -i extract/tests -o extract/tests -xo
